openapi: 3.0.0
info:
  title: Audit API
  description: Audit logs for stock management.
  version: "1.0"
paths:
  /audits:
    post:
      summary: Create a new audit log
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Audit'
      responses:
        '201':
          description: The audit log was successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Audit'
components:
  schemas:
    Audit:
      type: object
      properties:
        id:
          type: integer
          format: int64
        timestamp:
          type: string
          format: date-time
        userID:
          type: integer
          format: int64
        action:
          type: string
          enum: [CREATE, READ, UPDATE, DELETE]
        stockID:
          type: integer
          format: int64
        oldValue:
          type: string
        newValue:
          type: string
      required:
        - timestamp
        - action
        - stockID